config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'projects/new'

  resources :projects do
    resources :tasks
  end

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, :dependent => :delete_all
  validates :title, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates :description, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tasks, :dependent => :delete_all
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :firstname, presence: true
  validates :lastname, presence: true
  def fullname
    "#{firstname} #{lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :config_permitted_params, if: :devise_controller?

  protected

  def config_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :birthdate])
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :birthdate])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
    #render plain: params[:project].inspect
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:title, :date, :time)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(task_params)
  end

  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    if @task.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    #@task = Task.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_path(@project)
  end

private
  def task_params
    params.require(:task).permit(:description, :date, :state, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta data-app-slug="752-rocky-richard">
  <title>UniTasks Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<div class="topbar">
  <span class="home"><%= link_to 'UniTasks Web', root_path %></span>
  <span class="userinfo">Hello <%= link_to current_user.firstname, edit_user_registration_path %>!</span>
  <span class="userlogout"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></span>
</div>
<% end %>
<% if !notice.nil? %>
<p class="notice"><%= notice %></p>
<% end %>
<% if !alert.nil? %>
<p class="alert"><%= alert %></p>
<% end %>
<% if !current_user %>
<div class="uniheader"><h1>UniTasks Web</h1></div>
<% end %>
<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %> prevented the project from saving:
    </h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="editbox">
<%= form_for @project do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </p>

  <p>
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/projects/edit.html.erb
<div class="header">
<h1>Edit project</h1>
<%= link_to 'Back', project_path %>
</div>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="header">
<h1>Projects</h1>
<%= link_to 'New project', new_project_path %>
</div>
<% @projects.each do |project| %>
<div class="project_item">
  <p class="project_item_title"><%= link_to project.title, project_path(project) %></p>
  <p class="project_links">
    <span class="project_info">Due to: <%= project.date.strftime("%d.%m.%Y") %> | <%= project.time.strftime("%H:%M %Z") %></span>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Sicher?' }, :class => "delete" %>
  </p>
  <p class="project_item_stats">
    <span class="open">open: <%= Task.where(project_id: project.id).where(state: 'open').count %></span>
    <span class="inprogress">in progress: <%= Task.where(project_id: project.id).where(state: 'in progress').count %></span>
    <span class="finished">finished: <%= Task.where(project_id: project.id).where(state: 'finished').count %></span>
    <span class="overduestat">overdue: <%= Task.where(project_id: project.id).where("date < ?", Date.today).where().not(state: 'finished').count %></span>
  </p>
</div>
<% end %>

app/views/projects/new.html.erb
<div class="header">
<h1>New project</h1>
<%= link_to 'Back', projects_path %>
</div>
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="header">
<h1><%= @project.title %></h1>
<%= link_to 'Back', projects_path %> |
<%= link_to 'Edit', edit_project_path(@project) %>
<p>
  Due to: <%= @project.date.strftime("%d.%m.%Y") %> | <%= @project.time.strftime("%H:%M %Z") %>
</p>
<p class="project_item_stats">
  <span class="open">open: <%= Task.where(project_id: @project.id).where(state: 'open').count %></span>
  <span class="inprogress">in progress: <%= Task.where(project_id: @project.id).where(state: 'in progress').count %></span>
  <span class="finished">finished: <%= Task.where(project_id: @project.id).where(state: 'finished').count %></span>
  <span class="overduestat">overdue: <%= Task.where(project_id: @project.id).where("date < ?", Date.today).where().not(state: 'finished').count %></span>
</p>
</div>

<div class="taskscontainer">
<h2>Tasks</h2>
<%= render @project.tasks.where().not(state: "finished") %>
<%= link_to '+', new_project_task_path(@project), :class => "newtask" %>
<div class="hor_separator"></div>
<%= render @project.tasks.where(state: "finished") %>
</div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@task.errors.count, "error") %> prevented the task from saving:
    </h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="editbox">
<%= form_for [@project, @task] do |f| %>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </p>

  <p>
    <%= f.label :user %><br>
    <%= f.collection_select :user, User.all, :id, :firstname, prompt: true %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.select :state, [['offen'],['in Arbeit'],['fertig']] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/tasks/_task.html.erb
<% @task_css_class = "task_item" %>
<% if task.date < Date.today && task.state != 'finished'%>
  <% @task_css_class += " overdue" %>
<% end %>
<% if (Date.today + 1.days == task.date) || (Date.today == task.date) %>
  <% @task_css_class += " soon_tm" %>
<% end %>
<% if task.state == "finished" %>
  <% @task_css_class += " finished_bg" %>
<% end %>
<div class="<%= @task_css_class %>">
<div class="task_description">
<p>
  <%= task.description %>
</p>
</div>
<div class="task_info">
<p>
   Due to: <%= task.date.strftime("%d.%m.%Y") %>
</p>

<p>
  State: <%= task.state %>
</p>

<p>
  Editor: <%=  User.find(task.user_id).fullname %>
</p>
</div>
<div class="task_edit_buttons">
  <%= link_to 'Edit', edit_project_task_path(task.project, task) %>
  <%= link_to 'Delete', [task.project, task], method: :delete, data: { confirm: 'Sicher?' }, :class => "delete" %>
</div>
</div>

app/views/tasks/edit.html.erb
<div class="header">
<h1>Edit task</h1>
<%= link_to 'Back', project_path(@project) %>
</div>
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@task.errors.count, "error") %> prevented the task from saving:
    </h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="editbox">
<%= form_for [@project, @task] do |f| %>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </p>

  <p>
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :fullname, prompt: true %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.select :state, [['open'],['in progress'],['finished']] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/tasks/new.html.erb
<div class="header">
<h1>New Task</h1>
<%= link_to 'Back', project_path(@project) %>
</div>
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@task.errors.count, "error") %> prevented the task from saving:
    </h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="editbox">
<%= form_for [@project, @task] do |f| %>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </p>

  <p>
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :fullname, prompt: true %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.select :state, [['open'],['in progress'],['finished']] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>